Update use of cetmodules with $CETMODULES_DIR/tools/migrate

diff --git a/ups/setup_for_development b/ups/setup_for_development
--- a/ups/setup_for_development
+++ b/ups/setup_for_development
@@ -10,7 +10,7 @@
 #    set fw_db=/some/path; source /some/path/this_file
 # or  fw_db=/some/path; . /some/path/this_file
 #
-# Generated by cetmodules 2.16.02 at Thu Mar 25 20:53:32 CDT
+# Generated by cetmodules 3.09.03 at Wed Mar 30 08:58:19 CDT 2022
 ########################################################################
 
 ########################################################################
@@ -44,6 +44,7 @@ true && test $?shell = 1 && set _cetpkg_shell_flavor=csh || _cetpkg_shell_flavor
 test "$_cetpkg_shell_flavor" = csh && \
   set _cetpkg_nobuild="" && \
   set _cetpkg_shell_var_set=set\\1 && \
+  set _cetpkg_to_stderr="| sh -c 'cat 1>\\&2'" && \
   alias vecho_ 'if ($?vv == 1) echo \>\> \!*' && \
   alias unsetenv_ unsetenv && \
   alias tnotnull "eval '"'test $?'"\!* -eq 1' && eval '"'test -n "$'"\!*"'"'"'" && \
@@ -55,6 +56,7 @@ test "$_cetpkg_shell_flavor" = csh && \
 test "$_cetpkg_shell_flavor" = sh && \
   _cetpkg_nobuild="" && \
   _cetpkg_shell_var_set= && \
+  _cetpkg_to_stderr='1>\&2' && \
   eval 'vecho_() { test -n "${vv-}" && echo ">> $*"; return 0; }' && \
   eval 'setenv() { eval "$1=\"\${2-}\"; export $1"; }' && \
   eval 'unsetenv_() { unset "$@"; }' && \
@@ -137,8 +139,9 @@ setenv CETPKG_BUILD `/bin/pwd -P`
 #
 ########################################################################
 
-sed -Ee 's&\b__SET__([[:space:]]+)&'$_cetpkg_shell_var_set'&g' \
+sed -Ee 's&(^|[^[:alnum:]_])__SET__([[:space:]]+)&'$_cetpkg_shell_var_set'&g' \
   -e 's&__SETUP_ARGS__&'"$*"'&g' \
+  -e 's&__TO_STDERR__&'"$_cetpkg_to_stderr"'&g' \
   > ./setup_common.$_cetpkg_shell_flavor <<\__TOP_EOF__
 ########################################################################
 
@@ -183,6 +186,24 @@ test -z "$_cetpkg_status$_cetpkg_cetmsetup" && setenv PATH `dropit -sfe "$CETPKG
 test -z "$_cetpkg_status$_cetpkg_cettop" -a -n "$CETMODULES_DIR" && __SET__ _cetpkg_cettop="$CETMODULES_DIR"
 ####################################
 
+########################################################################
+# A bootstrapped Perl environment is only needed if we're building
+# cetmodules itself.
+
+test -n "$_cetpkg_status" || test -n "$CETMODULES_DIR" || \
+  setup cetpkgsupport
+test $? != 0 && __SET__ _cetpkg_status=1 && \
+  echo "ERROR: setup of cetpkgsupport has failed" || true
+test -n "$_cetpkg_status" || test -n "$CETMODULES_DIR" || \
+  "$_cetpkg_cettop/libexec/bootstrap-perl-env" > \
+  "$CETPKG_BUILD/bootstrap.log"
+test $? != 0 && __SET__ _cetpkg_status=1 && \
+  echo "ERROR: bootstrap of Perl environment for cetmodules has failed: see $CETPKG_BUILD/bootstrap.log" || true
+test -n "$_cetpkg_status" || test -n "$CETMODULES_DIR" || \
+  eval "`perl -I\"$CETPKG_BUILD/$CET_SUBDIR/CPAN/lib/perl5\" -Mlocal::lib=\"$CETPKG_BUILD/$CET_SUBDIR/CPAN\",\"$CETPKG_BUILD/$CET_SUBDIR/cpan_build\"\`test \$?shell = 1 && printf \",--shelltype=csh\"\``"
+test $? != 0 && __SET__ _cetpkg_status=1 && \
+  echo "ERROR: setup of Perl environment for cetmodules has failed" || true
+
 ####################################
 # Generate the setup script to set up dependencies.
 
@@ -225,7 +246,7 @@ test "$_cetpkg_shell_flavor" = csh && \
 # Finish cleanup and exit. Note the use of eval so we can unset
 # everything including $return and $_cetpkg_status.
 eval "unset vecho_ setenv unsetenv_ source tnotnull nullout "\
-"_cetpkg_nobuild _cetpkg_shell_var_set "\
+"_cetpkg_nobuild _cetpkg_shell_var_set _cetpkg_to_stderr"\
 "_cetpkg_fw_db _cetpkg_myself _cetpkg_mydir _cetpkg_cetmsetup "\
 "_cetpkg_cettop _cetpkg_setup _cetpkg_setup_errlog "\
 "_cetpkg_shell_flavor return _cetpkg_status; \
